# codeDeploy 자동 배포 설정 파일
version: 0.0     # (1)
os: linux
files:
  - source: /     # (2)
    destination: /home/ec2-user/app/step2/zip     # (3)
    overwrite: yes

# codeDeploy에서 EC2서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 함
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
