# codeDeploy 자동 배포 설정 파일
version: 0.0     # (1)
os: linux
files:
  - source: /     # (2)
    destination: /home/ec2-user/app/nonstop/zip     # (3)
    overwrite: yes

# codeDeploy에서 EC2서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 함
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# codeDeploy 배포 단계에서 실행할 명령어를 지정
# ApplicationStart 라는 단계에서 start.sh를 ec2-user 권한으로 실행
hooks:
  AfterInstall:
    - location: stop.sh     # nginx와 연결되어 있지 않은 스프링 부트를 종료한다.
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh    # nginx와 연결되어 있지 않은 port로 새 버전의 스프링 부트를 시작한다.
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh   # 새 스프링 부트가 정상적으로 실행됐는지 확인한다.
      timeout: 60
      runas: ec2-user