spring:
  profiles:
    group:
      "local": "localDB, devPort, secret, wev-mvc"
      "dev": "devDB, devPort, secret, web-mvc"
      "prod": "prodDB, prodPort, secret, web-mvc"
  datasource:
    url: jdbc:h2:tcp://localhost/~/Backend
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2.client:
      registration:
        google:
          clientId: 559041382443-adrtdjhdcbientq5gegg2t90uncfhqvm.apps.googleusercontent.com
          clientSecret: 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
          scope: profile, email
logging:
  level:
    org.hibernate.SQL: debug
jwt:
  secret: 0bd23166f2fd39744aeb25531eb77155290c53e5c44c4f3d872bb93cf5062c8260a3da93d1d9894dd1ee4a3e33053104a6ecbf4fbccc9cc73c2729d30ad886e9