spring:
  profiles:
    group:
      "local": "localDB, devPort, secret, wev-mvc"
      "dev": "devDB, devPort, secret, web-mvc"
      "prod": "prodDB, prodPort, secret, web-mvc"
  datasource:
    url: jdbc:h2:tcp://localhost/~/Backend
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug